server:
  port: 8888

spring:

  resources:
    add-mappings: true
    cache:
      cachecontrol:
        # 缓存相应时间，单位秒
        max-age: 3600
    chain:
      # 资源链启动缓存，默认启动
      cache: true
      # 启动资源链
      enabled: true
      # 启动压缩资源（gzip,brotli）解析，默认禁用
      compressed: true
    static-locations: classpath:/static/


  # 静态资源处理
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          # 缓存相应时间，单位秒
          max-age: 3600
      chain:
        # 资源链启动缓存，默认启动
        cache: true
        # 启动资源链
        enabled: true
        # 启动压缩资源（gzip,brotli）解析，默认禁用
        compressed: true
      static-locations: classpath:/static/

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    # 驱动类
    driver-class-name: com.mysql.jdbc.Driver
    # 数据源连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大活跃数
      max-active: 20
      # 配置获取连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL

  # thymeleaf 配置
  thymeleaf:
    # 禁用缓存
    cache: false

  redis:
    host: 192.168.73.131
    port: 6379
    #默认操作的数据库
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        ##最大空闲连接 默认 8
        max-idle: 200
        #最小空闲连接 默认0
        min-idle: 5

  rabbitmq:
    host: 192.168.73.133
    username: guest
    password: guest
    # 虚拟主机
    virtual-host: /
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息 处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认 true
        auto-startup: true
        # 被拒绝时重新进行队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000ms
        # 重试最大次数，默认为3
        max-attempts: 3
        # 重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        # 重试的间隔乘数。如果配2.0，每次重试的时间就乘以2倍
        multiplier: 1

mybatis-plus:
  # 配置 Mapper.xml 映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置类型别名
  type-aliases-package: com.flipped.seckill.pojo



# mybatis SQL 打印 （方法接口所在的包,不是.xml所在的包）
logging:
  level:
    com.flipped.seckill.mapper: debug
  file:
    name: run.log # 指定生成日志文件名称
    path: ./ # 将日志文件生成到当前目录（当前模块的目录中）


#mybatis:
#  # 配置 Mapper.xml 映射文件
#  mapper-locations: classpath:/mapper/*.xml
#  # 配置类型别名
#  type-aliases-package: cn.rtangyy.seckilling.pojo
#  # 开启驼峰命名法
#  configuration:
#    map-underscore-to-camel-case: true





